// <auto-generated />
namespace SnilAcademicDepartment.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DatabaseModel08062019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseModel08062019));
        
        string IMigrationMetadata.Id
        {
            get { return "201906081042279_DatabaseModel-08-06-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
