//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnilAcademicDepartment.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О студенческой научной лаборатории.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес: Курчатова 1, 220108, г. Минск, Республика Беларусь..
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международное сотрудничество.
        /// </summary>
        public static string Collaboration {
            get {
                return ResourceManager.GetString("Collaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша студенческая научная лаборатория поддерживает тесные контакты с ведущими зарубежными научными лабораториями и университетами. Среди них можно отметить Институт здоровья Люксембурга (LiH), Европейскую молекулярную биологическую лабораторию (EMBL) и др..
        /// </summary>
        public static string CollaborationIntro {
            get {
                return ResourceManager.GetString("CollaborationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра осуществляет научное сотрудничество с рядом зарубежных научных организаций, в том числе с:
        ///    &lt;p&gt;
        ///        &lt;ul style=&quot;margin-left:18pt&quot;&gt;
        ///            &lt;li&gt;EuroPhoton GmbH, Neusalza-Spremberg, Germany (краткосрочная стажировка Ска-куна В.В, июль 2018 г. без оформления командировки);
        ///            &lt;li&gt;Марбургский университет, Марбург, Германия (меморандум о сотрудничестве, стажировка ассистента кафедры Свидрицкого А.С., консультирование аспиранта);
        ///            &lt;li&gt;Рурский университет, Бохум, Германия [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CollaborationPage {
            get {
                return ResourceManager.GetString("CollaborationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания*.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        public static string ContactsForm {
            get {
                return ResourceManager.GetString("ContactsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница с контактными данными.
        /// </summary>
        public static string ContactsPage {
            get {
                return ResourceManager.GetString("ContactsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты с руководителями кафедры, администрацией. Ознакомьтесь с расположением лаборатории, кротчайшим пешим путём, на общественном, личном транспорте. На странице имеется возможность оставить текстовое сообщение..
        /// </summary>
        public static string ContactsShortDescription {
            get {
                return ResourceManager.GetString("ContactsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минск.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь вы можете познакомиться с библиотекой резюме выпукскников нашего факультета.
        /// </summary>
        public static string CVInto {
            get {
                return ResourceManager.GetString("CVInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать документ....
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обучение на кафедре.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образовательный процесс студентов. Здесь вы сможете найти описание образовательного процесса, список читаемых дисиплин, а также список текущих магистерских и дипломных работ..
        /// </summary>
        public static string EducationShortDescription {
            get {
                return ResourceManager.GetString("EducationShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. адрес*.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс. +375 17 398 7042..
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Белорусский государственный университет, СНИЛ &quot;Моделирования и анализа процессов и систем&quot;.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО*.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История СНИЛ.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История создания лаборатории, проводимые конференции и другая важная информация. На данной странице вы сможете найти подробное описание деятельности лаборатории и ознакомиться с достижениями ее участников..
        /// </summary>
        public static string HistoryShortDescription {
            get {
                return ResourceManager.GetString("HistoryShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БГУ СНИЛ .
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее....
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kobernykbeljr@gmail.com.
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состав СНИЛ.
        /// </summary>
        public static string ParticipantsSPMA {
            get {
                return ResourceManager.GetString("ParticipantsSPMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели и учебно-вспомогательный персонал кафедры. В данном разделе вы можете ознакомиться с преподавательским составом кафедры, узнать направления научной деятельности ее сотрудников..
        /// </summary>
        public static string PeopleShortDescription {
            get {
                return ResourceManager.GetString("PeopleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состав кафедры.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +375 17 398 7042; +375 17 398 0222. .
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел. :.
        /// </summary>
        public static string PhoneString {
            get {
                return ResourceManager.GetString("PhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о научных проектах, выполняемых силами сотрудников лаборатории и преподавателей кафедры..
        /// </summary>
        public static string ProjectsIntro {
            get {
                return ResourceManager.GetString("ProjectsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научно-исследовательские проекты сотрудников кафедры, студентов нашей лаборатории. Наши достижения. Здесь вы можете найти описание проектов, идей участников лаборатории и сотрудников кафедры системного анализа и компьютерного моделирования. Для очень важен результат проведенных исследований и дальнейшее применение реализованных проектов..
        /// </summary>
        public static string ProjectsShortDescription {
            get {
                return ResourceManager.GetString("ProjectsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научные исследовательские проекты.
        /// </summary>
        public static string SciProjects {
            get {
                return ResourceManager.GetString("SciProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семинары.
        /// </summary>
        public static string Seminars {
            get {
                return ResourceManager.GetString("Seminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список научных семинаров кафедры и студенческой научной лаборатории. Научные семинары проводятся на регулярной основе с приглашением известных ученых. Многие семинары проводятся с участием зарубежных ученых, а также выпускников кафедры, получивших научные степени и работающих за границей..
        /// </summary>
        public static string SeminarsShortDescription {
            get {
                return ResourceManager.GetString("SeminarsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состав СНИЛ.
        /// </summary>
        public static string SNIL {
            get {
                return ResourceManager.GetString("SNIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники студенческой научной лаборатории и ее руководящий состав. В данном разделе вы можете ознакомиться с руководителями лаборатории, а также со студентами,  магистрантами и аспирантами, работающими в ней..
        /// </summary>
        public static string SNILShortDescription {
            get {
                return ResourceManager.GetString("SNILShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема*.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенческая научно исследовательская лаборатория.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моделирования и анализа процессов и систем.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в Студентческую Научно-Исследовательскую Лабораторию &quot;Моделирования и анализа процессов и систем&quot;!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
