//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnilAcademicDepartment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SnilConfigurationSectionKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnilConfigurationSectionKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnilAcademicDepartment.Properties.SnilConfigurationSectionKeys", typeof(SnilConfigurationSectionKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfKeyAreasOnEducationPage.
        /// </summary>
        public static string NumberOfKeyAreasOnEducationPageKey {
            get {
                return ResourceManager.GetString("NumberOfKeyAreasOnEducationPageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfLeadersOnHallOfFame.
        /// </summary>
        public static string NumberOfLeadersOnHallOfFameKey {
            get {
                return ResourceManager.GetString("NumberOfLeadersOnHallOfFameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfLecturesOnPageLectures.
        /// </summary>
        public static string NumberOfLecturesOnPageLecturesKey {
            get {
                return ResourceManager.GetString("NumberOfLecturesOnPageLecturesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfQuickLearningBlocksOnPage.
        /// </summary>
        public static string NumberOfQuickLearningBlocksOnPageKey {
            get {
                return ResourceManager.GetString("NumberOfQuickLearningBlocksOnPageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfSeminarsOnPageSeminars.
        /// </summary>
        public static string NumberOfSeminarsOnPageSeminarsKey {
            get {
                return ResourceManager.GetString("NumberOfSeminarsOnPageSeminarsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPagePreviewsEndIndex.
        /// </summary>
        public static string ProjectPagePreviewsEndIndexKey {
            get {
                return ResourceManager.GetString("ProjectPagePreviewsEndIndexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPagePreviewsStartIndex.
        /// </summary>
        public static string ProjectPagePreviewsStartIndexKey {
            get {
                return ResourceManager.GetString("ProjectPagePreviewsStartIndexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectsPreviewsEndIndex.
        /// </summary>
        public static string ProjectsPreviewsEndIndexKey {
            get {
                return ResourceManager.GetString("ProjectsPreviewsEndIndexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectsPreviewsStartIndex.
        /// </summary>
        public static string ProjectsPreviewsStartIndexKey {
            get {
                return ResourceManager.GetString("ProjectsPreviewsStartIndexKey", resourceCulture);
            }
        }
    }
}
