//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnilAcademicDepartment.Resources.PersonsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnilAcademicDepartment.Resources.PersonsResources.PersonsResource", typeof(PersonsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абитуриенты.
        /// </summary>
        public static string Abitur {
            get {
                return ResourceManager.GetString("Abitur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподавательский состав.
        /// </summary>
        public static string AcademicStaff {
            get {
                return ResourceManager.GetString("AcademicStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебно вспомогательный персонал.
        /// </summary>
        public static string AcademicSupportStaff {
            get {
                return ResourceManager.GetString("AcademicSupportStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ученое звание.
        /// </summary>
        public static string AcademicTitle {
            get {
                return ResourceManager.GetString("AcademicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата назначения.
        /// </summary>
        public static string AssignmentDate {
            get {
                return ResourceManager.GetString("AssignmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степень.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес эл. почты.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доска почета.
        /// </summary>
        public static string HallFame {
            get {
                return ResourceManager.GetString("HallFame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доска почета с представленными на ней лучшими преподавателями и студентами нашего кафедры системного анализа и компьютерного моделирования.
        /// </summary>
        public static string HallFameDescription {
            get {
                return ResourceManager.GetString("HallFameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магистры.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктора наук.
        /// </summary>
        public static string PhD {
            get {
                return ResourceManager.GetString("PhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус профессии.
        /// </summary>
        public static string ProfessionStatus {
            get {
                return ResourceManager.GetString("ProfessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессора.
        /// </summary>
        public static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата увольнения.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенты.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
    }
}
