//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnilAcademicDepartment.Resources.EducationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EducationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EducationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnilAcademicDepartment.Resources.EducationResources.EducationResource", typeof(EducationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие курсы и курсы по выбору.
        /// </summary>
        public static string CommonLectures {
            get {
                return ResourceManager.GetString("CommonLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата семинара.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дипломная работа.
        /// </summary>
        public static string Dimplom {
            get {
                return ResourceManager.GetString("Dimplom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дипломные и магистерские работы.
        /// </summary>
        public static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DiplomaDescription {
            get {
                return ResourceManager.GetString("DiplomaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string DiplomaNameTitle {
            get {
                return ResourceManager.GetString("DiplomaNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string DiplomaNoTableData {
            get {
                return ResourceManager.GetString("DiplomaNoTableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата защиты.
        /// </summary>
        public static string DiplomaProtectionDate {
            get {
                return ResourceManager.GetString("DiplomaProtectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string DiplomaTypeTitle {
            get {
                return ResourceManager.GetString("DiplomaTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключевые направления.
        /// </summary>
        public static string KeyDirections {
            get {
                return ResourceManager.GetString("KeyDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсовая работа.
        /// </summary>
        public static string Kurs {
            get {
                return ResourceManager.GetString("Kurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекции.
        /// </summary>
        public static string Lectures {
            get {
                return ResourceManager.GetString("Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читает лекции.
        /// </summary>
        public static string LectureSpeaker {
            get {
                return ResourceManager.GetString("LectureSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магистерская диссертация.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственные.
        /// </summary>
        public static string ResponsiblePerson {
            get {
                return ResourceManager.GetString("ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семинары.
        /// </summary>
        public static string Seminars {
            get {
                return ResourceManager.GetString("Seminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выступил.
        /// </summary>
        public static string SeminarSpeaker {
            get {
                return ResourceManager.GetString("SeminarSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальные курсы.
        /// </summary>
        public static string SpecialCourses {
            get {
                return ResourceManager.GetString("SpecialCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальность.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тематика.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
